# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - mockinterviewapp-backend-takashi01

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x' # Set to 18.x to match your Azure App Service setting. You can test 22.x later if needed.

      - name: npm install, build, and test # This step still runs local install for building/testing on GitHub runner
        run: |
          npm ci
          npm run build --if-present
          npm run test --if-present
        env: # <--- ADD THIS BLOCK HERE
          DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      - name: Zip artifact for deployment
        run: |
          # IMPORTANT CHANGE: Exclude node_modules from the zip. Azure will install them directly on the server.
          # This ensures a clean installation of dependencies in the Azure environment.
          # Also exclude any common development-only files or directories you don't need in production like .env files.
          zip -r release.zip . -x ".git/*" ".github/workflows/*" "node_modules/*" ".env"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      contents: read
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      - name: Unzip artifact for deployment
        run: unzip release.zip
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          auth-type: SERVICE_PRINCIPAL
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2 # v2のままです
        with:
          app-name: 'mockinterviewapp-backend-takashi01'
          slot-name: 'Production'
          package: .
          # IMPORTANT CHANGE: enable-oryx-build は削除します

          # Instead, use startup-command to run npm install and node server.js
          startup-command: 'npm install && node server.js' # <-- Add or modify the line! Overwrite this and
          # Also, ensure your Azure App Service's 'Configuration' -> 'Application settings'
          # have DB_CONNECTION_STRING and GOOGLE_API_KEY set for runtime.

          # 代わりに startup-command を使って npm install と node server.js を実行します
          startup-command: 'npm install && node server.js' # <-- この行を追加・修正します！

