# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - mockinterviewapp-backend-takashi01

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x' # Set to 18.x to match your Azure App Service setting. You can test 22.x later if needed.

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: |
          # Zip the contents of the current directory (your repo root)
          # This assumes package.json, server.js, node_modules etc., are at the root level of your Git repository.
          # Exclude the .git directory and the workflow files themselves from the zip
          zip -r release.zip . -x ".git/*" ".github/workflows/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production' # This environment name must exactly match the "GitHub environment name" you configured in Azure Federated Credentials.
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This permission is crucial for OpenID Connect (OIDC) authentication.
      contents: read
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      - name: Unzip artifact for deployment
        run: unzip release.zip
      - name: Login to Azure
        uses: azure/login@v2
        with:
          # For OIDC authentication (due to 'id-token: write' permission),
          # 'client-id', 'tenant-id', and 'client-secret' are NOT passed directly here.
          # Azure AD's Federated Credentials handle the authentication based on the OIDC token.
          # We only need to provide the subscription-id to the login action.
          azure-subscription: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2893712FC95E4564961A934DD6F6ED75 }}
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mockinterviewapp-backend-takashi01'
          slot-name: 'Production'
          package: . # Deploy the contents of the current directory (which is where the unzipped artifact resides)
          # Important: Ensure 'enable-oryx-build' and 'scm-do-build-during-deployment' are NOT present here.
